#!/bin/bash
# Quick Marketplace Registration Helper
# Run this to get started with marketplace listings

echo "=========================================="
echo "  CashClaw Marketplace Registration"
echo "=========================================="
echo ""
echo "Your Services:"
echo "  1. SEO Auditor - $9/$29/$59"
echo "  2. Lead Generator - $9/$15/$25"
echo "  3. Social Media Manager - $9/$19/$49"
echo ""
echo "Payment Wallet:"
echo "  0x6a649D1D089963AAD808a5Ba9ff9EbF9E48a8268"
echo "  Network: Base (USDC)"
echo ""
echo "=========================================="
echo "  Quick Registration Links"
echo "=========================================="
echo ""
echo "1. CONTRA (Recommended - Crypto Friendly)"
echo "   URL: https://contra.com/signup"
echo "   Time: 5 minutes"
echo "   Fees: 0% (no platform fees!)"
echo ""
echo "2. FIVERR"
echo "   URL: https://www.fiverr.com/start_selling"
echo "   Time: 15 minutes per gig"
echo "   Fees: 20% of each sale"
echo ""
echo "3. UPWORK"
echo "   URL: https://www.upwork.com/nx/signup"
echo "   Time: 30 minutes profile + 24-48h approval"
echo "   Fees: 10% of each sale"
echo ""
echo "=========================================="
echo "  Sample Portfolio Files Created:"
echo "=========================================="
echo ""
echo "  • portfolio/sample-seo-audit.md"
echo "  • portfolio/sample-leads.json"
echo "  • portfolio/sample-social-calendar.md"
echo ""
echo "Use these as examples when creating listings."
echo ""
echo "=========================================="
echo "  Next Steps:"
echo "=========================================="
echo ""
echo "1. Open browser and register on Contra"
echo "2. Create your first service listing"
echo "3. Share your profile in crypto communities"
echo "4. Check AGENTS_STATUS.md for service details"
echo ""
echo "Good luck! 🚀"
echo ""
